components:
  schemas:
    FacetComparisonRequest:
      properties:
        cohort1:
          additionalProperties: true
          title: Cohort1
          type: object
        cohort2:
          additionalProperties: true
          title: Cohort2
          type: object
        doc_type:
          title: Doc Type
          type: string
        facets:
          items: {}
          title: Facets
          type: array
        interval:
          default: 0
          title: Interval
          type: number
      required:
      - doc_type
      - cohort1
      - cohort2
      - facets
      title: FacetComparisonRequest
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    IntersectionRequest:
      properties:
        cohort1:
          additionalProperties: true
          title: Cohort1
          type: object
        cohort2:
          additionalProperties: true
          title: Cohort2
          type: object
        doc_type:
          title: Doc Type
          type: string
        precision_threshold:
          default: 3000
          title: Precision Threshold
          type: integer
      required:
      - doc_type
      - cohort1
      - cohort2
      title: IntersectionRequest
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: Gen3 Analysis Service
  version: 1.0.0
openapi: 3.1.0
paths:
  /:
    get:
      description: Directs client to the docs
      operationId: redirect_to_docs__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get swagger docs
      tags:
      - Basic
  /_status/:
    get:
      description: Gets the current status of the service
      operationId: get_status__status__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: No content
        '500':
          description: No content
      summary: Get service status
      tags:
      - Basic
  /_version/:
    get:
      description: Gets the current version of the service
      operationId: get_version__version__get
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: true
                title: Response Get Version  Version  Get
                type: object
          description: No content
      summary: Get current version
      tags:
      - Basic
  /compare/facets:
    post:
      description: "Compare facets between two cohorts.\n\nArgs:\n    doc_type: the\
        \ cohorts' ES document type\n    cohort1: filter corresponding to the first\
        \ cohort to compare\n    cohort2: filter corresponding to the second cohort\
        \ to compare\n    facets: fields to compare\n    interval: TODO\n\nReturns:\n\
        \    dict - example:\n\n        {\n            \"cohort1\": {\n          \
        \      \"facets\": {\n                    \"my_field\": {\n              \
        \          {\"key\": \"value1\", \"count\": 99},\n                       \
        \ {\"key\": \"value2\", \"count\": 45},\n                    },\n        \
        \        }\n            },\n            \"cohort2\": {\n                \"\
        facets\": {\n                    \"my_field\": {\n                       \
        \ {\"key\": \"value1\", \"count\": 100},\n                        {\"key\"\
        : \"value2\", \"count\": 44},\n                    },\n                }\n\
        \            },\n        }"
      operationId: compare_facets_compare_facets_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FacetComparisonRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: true
                title: Response Compare Facets Compare Facets Post
                type: object
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Compare Facets
      tags:
      - Compare
  /compare/intersection:
    post:
      description: "Get the number of documents at the intersection between two cohorts,\
        \ as well as the number\nof documents that only belong to either one of the\
        \ cohorts. Useful to generate Venn diagrams.\n\nArgs:\n    doc_type: the cohorts'\
        \ ES document type\n    cohort1: filter corresponding to the first cohort\
        \ to compare\n    cohort2: filter corresponding to the second cohort to compare\n\
        \    precision_threshold (default: 3000): option to trade memory for accuracy\
        \ when querying cardinality in ES\n\nReturns:\n    dict - example:\n\n   \
        \     {\n            \"cohort1\": {\n                \"facets\": {\n     \
        \               \"my_field\": {\n                        {\"key\": \"value1\"\
        , \"count\": 99},\n                        {\"key\": \"value2\", \"count\"\
        : 45},\n                    },\n                }\n            },\n      \
        \      \"cohort2\": {\n                \"facets\": {\n                   \
        \ \"my_field\": {\n                        {\"key\": \"value1\", \"count\"\
        : 100},\n                        {\"key\": \"value2\", \"count\": 44},\n \
        \                   },\n                }\n            },\n        }"
      operationId: get_cohort_intersection_compare_intersection_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntersectionRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: true
                title: Response Get Cohort Intersection Compare Intersection Post
                type: object
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Cohort Intersection
      tags:
      - Compare
